export const scowldMonetization = {
  creditDefinition: "1 credit = 1 full voice turn",
  reservedCostPerCreditUSD: 0.08,
  subscriptions: [
    {
      id: "weekly",
      productId: "scowld.sub.weekly",
      title: "Weekly",
      priceUSD: 9.99,
      includedCredits: 40,
      weeklyRefillCredits: 40,
      refill: "40 credits/week",
    },
    {
      id: "monthly",
      productId: "scowld.sub.monthly",
      title: "Monthly",
      priceUSD: 34.99,
      includedCredits: 180,
      weeklyRefillCredits: 45,
      refill: "45 credits/week",
    },
    {
      id: "yearly",
      productId: "scowld.sub.yearly",
      title: "Yearly",
      priceUSD: 299.99,
      includedCredits: 2340,
      weeklyRefillCredits: 45,
      refill: "45 credits/week",
    },
  ],
  extraCreditPacks: [
    { id: "credits_10", productId: "scowld.credits.10", credits: 10, priceUSD: 3.99 },
    { id: "credits_50", productId: "scowld.credits.50", credits: 50, priceUSD: 14.99 },
    { id: "credits_100", productId: "scowld.credits.100", credits: 100, priceUSD: 27.99 },
    { id: "credits_200", productId: "scowld.credits.200", credits: 200, priceUSD: 49.99 },
    { id: "credits_500", productId: "scowld.credits.500", credits: 500, priceUSD: 119.99 },
  ],
  usagePolicy: {
    maxInputAudioSeconds: 20,
    maxTTSCharactersPerReply: 700,
    maxActiveRequests: 1,
    maxRepliesPerTenMinutes: 15,
    extraCreditsBypassSubscriptionRefill: true,
  },
} as const;
